### ISSUE TITLE
Vagrant installation fails 

### ISSUE THREAD

**Issue by bnasif25** [Parallels/parallels-vscode-extension#22]
**Describe the bug**
The extension is installed and starts checking for dependencies. Finds vagrant is not installed and starts to install but installation fails 

**To Reproduce**
1. Install extension 
2. When prompted to install Vagrant
3. See error

**Expected behavior**
Vagrant should be installed successfully

**Screenshots**

![image](https://github.com/Parallels/parallels-vscode-extension/assets/66963553/bd4ca9e4-d661-4cf3-a21f-2455e6679f0a)

**Extension Version**
v0.0.7 preview

**Comment by kmathoora** [comment]
Reproducible 1/5 times on x86_64 platform V0.0.8 preview, could not reproduce it again.
