### ISSUE TITLE
I am able to move group in a group 

### ISSUE THREAD

**Issue by bnasif25** [Parallels/parallels-vscode-extension#23]
**Describe the bug**
I created a group of VM1 and then created another group of VM.2 I was able to move the VM1 group into the VM2 group but the UI crashed 

**To Reproduce**
1. Created 2 groups with at least one VM inside
2. Drag one of the groups into the other group

**Expected behavior**
I should not be able to move a group into another group.

**Screenshots**

![image](https://github.com/Parallels/parallels-vscode-extension/assets/66963553/8f16d68b-0647-49b0-a39c-88a81f9068b7)

**Extension Version**
v0.0.7 Preview

**Comment by kmathoora** [comment]
Reproducible on V0.0.8 x86_64 platform
