### ISSUE TITLE
Unable to create Ubuntu VM 

### ISSUE THREAD

**Issue by bnasif25** [Parallels/parallels-vscode-extension#28]
**Describe the bug**
I am unable to create Ubuntu VM from the extension. I have tried to install it with UI, with User Interface, and with Vagrant Box. All three instances result in an error "Error creating VM: Error generating packer file"

**To Reproduce**
1. Open extension
2. Click on the "+" sign and choose operating system Linux, distribution choose ubuntu, and version 22.04
3. Click on Generate vm

**Expected behavior**
VM is created with selected settings 

**Screenshots**
![image](https://github.com/Parallels/parallels-vscode-extension/assets/66963553/70ae2630-8cc1-4c4f-9099-cba6da66eeb6)

**Extension Version**
'v0.0.8' preview

**Comment by kmathoora** [comment]
Same issue on x86_64 platform
