### ISSUE TITLE
Port the extension to JetBrains IntelliJ IDEs

### ISSUE THREAD

**Issue by rakleed** [Parallels/parallels-vscode-extension#52]
**Is your feature request related to a problem? Please describe.**
When writing code in JetBrains IntelliJ IDEs, there is no plugin like for VS Code.

**Describe the solution you'd like**
Port the extension to JetBrains IntelliJ IDEs.

**Additional context**
https://plugins.jetbrains.com/docs/intellij/developing-plugins.html#gradle-intellij-plugin

**Comment by cjlapao** [comment]
@rakleed We looked at this and unfortunately IntelliJ plugins are written in java and there is not an easy conversion between what we have and that language, we are noting this but putting it on the back burner unless we get a lot of upvotes.

Thanks

**Comment by rakleed** [comment]
> IntelliJ plugins are written in java

Also in Kotlin, but yes, it is not JS/TS.
