### ISSUE TITLE
Edit code all in one place

### ISSUE THREAD

**Issue by samegbor19** [Parallels/parallels-vscode-extension#62]
**Is your feature request related to a problem? Please describe.**
Currently unable to edit code stored on the virtual machine from the instance of vscode running the host. in my case macos 

**Describe the solution you'd like**
The ability to edit code all from one instance of the vscode running outside of the virtual machine would be great. Current ability exist to step into the VM instance but no ability to edit the code exists 

**Additional context**

**Comment by cjlapao** [comment]
@samegbor19 

We have some questions on this:

If the objective is to open files inside the VM, wouldn't the shared folders be a better option?
What would be the disadvantage of the shared folders vs this new feature?

Thanks

**Comment by cjlapao** [comment]
Closing this as it seems stale
