### ISSUE TITLE
Wrong extensions storage location

### ISSUE THREAD

**Issue by alexanderxc** [Parallels/parallels-vscode-extension#97]
**Is your feature request related to a problem? Please describe.**
Apparently this extensions saves data in `$HOME` and not in the `$HOME/.vscode/extensions/` folder

**Describe the solution you'd like**
Avoid cluttering `$HOME`

**Additional context**
N/A

**Comment by cjlapao** [comment]
@alexanderxc That is per design. We cannot use the `~/.vscode/extensions' folder as that folder only contains the extension code, and we need to persist some files, like the user profile.

This is inline with other extensions that save data outside of that folder.

the folder created should also not show in he finder as it is hidden as a few more that you have in your home folder.

We also provide settings where you can set that folder somewhere else
![image](https://github.com/Parallels/parallels-vscode-extension/assets/17143029/90404195-de4e-4e27-8ae6-2870d90674ca)
